### PR TITLE
Set and clear XML_CATALOG_FILES on activation and deactivation, respectively (take 2)

### PR DESCRIPTION
**Pull request by hattne**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Ensured the license file is being packaged.

Hopefully addresses all issues previously raised in botched #82 and includes fixes from #84 and #85 (which appears to have gone dormant).

### CODE REVIEW

**Comment by hattne** [comment]
@conda-forge-admin, please rerender

**Comment by hattne** [comment]
Is there anything I can do to move this forward? Until something like this is in place I don't think we can effectively use stylesheets through `libxml2`.

**Comment by gillins** [comment]
> I tried to rerender for you, but it looks like I wasn't able to push to the main branch of hattne/libxml2-feedstock. Did you check the "Allow edits from maintainers" box?

Any chance you could do this so it re-renders? All looks good to me, although I must admit I got kind of lost in the original discussion.

**Comment by ocefpaf** [comment]
@hattne I got

```
conda activate WAFO                                                                                             
/envs/TEST/etc/conda/activate.d/libxml2_activate.sh:export:12: not valid in this context: XML_CATALOG_FILES+
```

when using this package. Looks like we will need to pull them and get back to the drawing board.

**Comment by hattne** [comment]
> conda activate WAFO                                                                                             
> /envs/TEST/etc/conda/activate.d/libxml2_activate.sh:export:12: not valid in this context: XML_CATALOG_FILES+

Is this ZSH by any chance?

**Comment by ocefpaf** [comment]
> Is this ZSH by any chance?

Yes.

**Comment by ocefpaf** [comment]
Thanks for tacking this @hattne! Sorry I cannot be of much help.

**Pull request merged**
