### PR TITLE
Update to 2.9.4

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jschueller everything but `Python 3.5` is failing on Windows. That is probably due to Visual Studio.
If you are keen enough on Windows you can try to create patches. ([Here](https://github.com/conda-forge/libnetcdf-feedstock/pull/5/commits/7012ff69c4ce49a725a4bfcb2d2fb8b1c7525142) is a similar situation where @gillins fixed `libnetcdf` build on Windows.)

However, if Windows is not your thing can you add the proper `skip`s pre-selectors here and we can merge this.

**Comment by jschueller** [comment]
@ocefpaf, ok done, the -p1 patch was not accepted by conda anyway (this is annoying)
could you restart the travis build ? seems it got stuck.

**Comment by ocefpaf** [comment]
> @ocefpaf, ok done, the -p1 patch was not accepted by conda anyway (this is annoying)

Yeah. It would be nice to fix that in `conda-build`.

> could you restart the travis build ? seems it got stuck.

Not stuck but backlogged... We'll have to wait for a few hours. I will keep an eye here and merge this (or ping you again) once the CIs are done.

Thanks @jschueller!

**Comment by jschueller** [comment]
it passed!

**Comment by jakirkham** [comment]
Thanks @jschueller and @ocefpaf.

**Pull request merged**
