### PR TITLE
remove recently added build deps

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

remove some more build deps per problems still found after #99 

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
hmmm
```
2023-05-17T20:31:50.3033653Z configure:4259: ./conftest
2023-05-17T20:31:50.3034029Z ./conftest: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
```

**Comment by akrherz** [comment]
optimistic this will be green, famous last words...

**Comment by gillins** [comment]
Still getting this (why we added in the first place), but seems to succeed?
```
checking for python-3.10... no
configure: error: Package requirements (python-3.10) were not met:

No package 'python-3.10' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PYTHON_CFLAGS
and PYTHON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by akrherz** [comment]
@gillins This repo provides a c system library and not a python package, so we would not want it to try to build anything python related.  maybe passing --without-python would make that harmless configure error go away?

**Comment by gillins** [comment]
We already do that here: https://github.com/conda-forge/libxml2-feedstock/blob/main/recipe/build.sh#L24

I assumed Python was required by the build itself.

If you are happy go ahead and merge, probably not worth worrying about the details. One other thing I possibly should have done is move it to `cmake` with this migration, but low on time ATM.

**Comment by akrherz** [comment]
@gillins It appears the right flag is "--with-python=no", shrug.  Trying that now

**Comment by gillins** [comment]
Same message... weird.

**Comment by akrherz** [comment]
Eh, will save it for another day. Look good to take?

**Comment by gillins** [comment]
Yep go for it

**Comment by akrherz** [comment]
> Yep go for it

Well, I'm not a repo maintainer :)

**Comment by gillins** [comment]
Done! Thanks @akrherz

**Pull request merged**
