### PR TITLE
Avoid unbound variables in activation scripts

### PR DESCRIPTION
**Pull request by chrisburr**
Looks like this was already noticed in https://github.com/conda-forge/libxml2-feedstock/pull/82 so I won't explain 😄

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
From https://github.com/conda-forge/libxslt-feedstock/pull/36 I don't understand why this isn't being done with compile time flags instead? (In fact it looks like it should already be doing)

The PR description mentions:

>  Compile-time defaults cannot be used, because the value of XML_CATALOG_FILES will depend on the name of the environment where it is installed.

but that should be handled by conda's prefix replacement? @hattne can you clarify?

**Comment by celestinoamado** [comment]
Thanks, @chrisburr! 😄
Can you please add the `@echo off` at the top of recipe/activate.bat and recipe/desactivate.bat
That was also noticed in #82 (regarding Windows OS).

**Comment by hattne** [comment]
> 



> From [conda-forge/libxslt-feedstock#36](https://github.com/conda-forge/libxslt-feedstock/pull/36) I don't understand why this isn't being done with compile time flags instead? (In fact it looks like it should already be doing)
> 
> The PR description mentions:
> 
> > Compile-time defaults cannot be used, because the value of XML_CATALOG_FILES will depend on the name of the environment where it is installed.
> 
> but that should be handled by conda's prefix replacement? @hattne can you clarify?

The default catalog path in the `libxml2 `sources is derived from `SYSCONFDIR`, which is determined at compile time. Unless the root of the build environment is identical to the root of the environment at runtime (and `SYSCONFDIR `is the same in both environments), the built-in catalog path will be not work. As far as I can see, there is no reasonable way conda's prefix replacement could handle arbitrary hardcoded strings compiled into a binary.

**Comment by chrisburr** [comment]
> As far as I can see, there is no reasonable way conda's prefix replacement could handle arbitrary hardcoded strings compiled into a binary.

Unless I've misunderstood this is exactly what conda's prefix replacement should do. Conda-build uses a very long install prefix so that at install time conda can replace `$LONG_PREFIX/something{NULL BYTE}` with `$INSTALL_PREFIX/something{NULL BYTE plus extra null byte padding if needed}`.

**Comment by celestinoamado** [comment]
@chrisburr, do you think it is possible to add the `@echo off` at the top of recipe/activate.bat and recipe/deactivate.bat ? Thanks!

**Comment by hattne** [comment]
> > As far as I can see, there is no reasonable way conda's prefix replacement could handle arbitrary hardcoded strings compiled into a binary.
> 
> Unless I've misunderstood this is exactly what conda's prefix replacement should do. Conda-build uses a very long install prefix so that at install time conda can replace `$LONG_PREFIX/something{NULL BYTE}` with `$INSTALL_PREFIX/something{NULL BYTE plus extra null byte padding if needed}`.

I stand corrected: I did not understand the full extent of conda prefix replacement (I am, however, still unconvinced it is reasonable). Better figure out why it was not working in the first place…

**Comment by hattne** [comment]
Windows does need a fix, because there `SYCONFDIR` is not set; I'll come up with some kind of patch for that. As to what went wrong on Unix, I cannot say: at this stage my best guess is that I was inadvertently running `xsltproc` from the host operating system rather than the one from conda.

**Comment by hattne** [comment]
I did actually write patch to set `SYSCONFDIR` on Windows but it's useless in this context, because it appears prefix-replacement in binaries [is done differently on Windows](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#detect-binary-files-with-prefix). As noted by @chrisburr, this PR [is not necessary on Unix](https://github.com/conda-forge/libxml2-feedstock/pull/85#issuecomment-1381808361), but it may still make sense in order to have the package behave identically on all platforms.

To progress, I think `activate.{bat,ps1,sh}` should append `${PREFIX}/etc/xml/catalog` to `XML_CATALOG_FILES`, using space as a separator. Per @isuruf's comment, `activate.sh` should additionally append the [system location](https://github.com/conda-forge/libxml2-feedstock/pull/82#discussion_r1065733007) (`/etc/xml/catalog`) on Unix. For space-separation to work, all paths probably need to be URL-encoded.

I'll try that next.

**Comment by hattne** [comment]
Obsolete as of #87.

**Pull request closed without merging**
