### PR TITLE
drop python from host, cleanup libiconv

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

having python 3.10 requirement in host seems to be causing troubles conda-forge/postgresql-feedstock#160

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
(windows build failed without iconv requirement, added back on all platforms)

**Comment by ocefpaf** [comment]
It was not passing without those before. I wonder what changed. Anyway, big +1 for this. Let's merge!

**Comment by ryanvolz** [comment]
I'm still seeing solver errors even after this ([example](https://github.com/conda-forge/libiio-feedstock/pull/18)), and it looks like the original test case is the same: https://github.com/conda-forge/postgresql-feedstock/pull/160. The osx-arm64 and linux-aarch64 packages still have a Python dependency, and I think this is because cross-python also needs to be removed from the build deps.

**Comment by akrherz** [comment]
@ryanvolz All well with your world now?  #100 fixed things up for me.

**Comment by ryanvolz** [comment]
> @ryanvolz All well with your world now? #100 fixed things up for me.

Yep, good now!

**Pull request merged**
