### PR TITLE
Set and clear XML_CATALOG_FILES on activation and deactivation, respectively

### PR DESCRIPTION
**Pull request by hattne**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

From https://github.com/conda-forge/libxslt-feedstock/pull/36.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@hattne not that we will probably need to reset after merging this. See https://conda-forge.org/status/ and https://github.com/conda-forge/status/issues/137 on how to do this, if you have the extra time.

**Comment by celestino-amado** [comment]
This changes are causing an issue on Windows OS: the Anaconda Prompt (cmd) started behaving not as expected when lauching and after using conda commands. 

To fix it:
- just need to change recipe/activate.bat to start lines 1 and 2 with @
(use @set instead of set) 
- and change recipe/desactivate.bat to start lines 1, 2, 4 and 6 with @
(use @if instead of if and use @set instead of set)

**Comment by hattne** [comment]
> * just need to change recipe/activate.bat to start lines 1 and 2 with @
>   (use @set instead of set)
> * and change recipe/desactivate.bat to start lines 1, 2, 4 and 6 with @
>   (use @if instead of if and use @set instead of set)

Would `@echo off` at the top of both files be a cleaner solution?

**Comment by celestino-amado** [comment]
> > * just need to change recipe/activate.bat to start lines 1 and 2 with @
> >   (use @set instead of set)
> > * and change recipe/desactivate.bat to start lines 1, 2, 4 and 6 with @
> >   (use @if instead of if and use @set instead of set)
> 
> Would `@echo off` at the top of both files be a cleaner solution?

I suppose that `@echo off` could work as well.

However, I notice that the .bat files in condabit folder inside anaconda don't use `@echo off` but instead @ at each line.

**Comment by celestino-amado** [comment]
@hattne, yes, adding the `@echo off` at the top of recipe/activate.bat and recipe/desactivate.bat is an nice solution, I had already tested it and works. Thanks!

**Comment by acaprez** [comment]
Just an FYI, this change causes issues in environments that have unset variable checking (i.e. `set -u`) enabled:
```
/anaconda/etc/conda/activate.d/libxml2_activate.sh: line 3: XML_CATALOG_FILES: unbound variable
```

**Comment by celestino-amado** [comment]
@hattne , I had noticed that in Windows OS there is no folder `etc/xml/catalog` in my Anaconda installation. 
Since the purpose of this changes are to create/change the environment variable `XML_CATALOG_FILES` to be assigned to `etc/xml/catalog`, does it still makes sense make this changes for Windows OS?
For exemple, I cite the following reference in [http://www.sagehill.net/docbookxsl/UseCatalog.html](http://www.sagehill.net/docbookxsl/UseCatalog.html)

> By default, xsltproc looks for an XML catalog file named /etc/xml/catalog (**except on Windows, for which there is no default location**)

**Comment by celestino-amado** [comment]
@hattne , I had noticed that in Windows OS there is no folder `etc/xml/catalog` in Anaconda installation. 
Since the purpose of this changes are to create/change the environment variable `XML_CATALOG_FILES` to be assigned to `etc/xml/catalog`, does it still makes sense apply this changes for Windows OS?
For exemple, I cite the following reference in [http://www.sagehill.net/docbookxsl/UseCatalog.html](http://www.sagehill.net/docbookxsl/UseCatalog.html) where Windows is excluded from assigning `XML_CATALOG_FILES=etc/xml/catalog` (as there is no xsltproc catalog folder `etc/xml/catalog` in Windows)

> By default, xsltproc looks for an XML catalog file named /etc/xml/catalog (**except on Windows, for which there is no default location**)

**Comment by g-rutter** [comment]
@hattne this breaks my org's workflow with the error @acaprez pointed out. Could we please check for the existence of the variable before access? Something like 
```bash
export xml_catalog_files_libxslt="${XML_CATALOG_FILES:-}"
```
might be what you want.

**Comment by jakirkham** [comment]
Note: These packages have been marked broken ( https://github.com/conda-forge/admin-requests/pull/649 )

**Comment by hattne** [comment]
> @hattne , I had noticed that in Windows OS there is no folder `etc/xml/catalog` in Anaconda installation. Since the purpose of this changes are to create/change the environment variable `XML_CATALOG_FILES` to be assigned to `etc/xml/catalog`, does it still makes sense apply this changes for Windows OS?

I think yes, because it provides the path to where other packages will read or write catalog information. `libxml2` itself does not provide any catalogs, just the infrastructure to manipulate them and `XML_CATALOG_FILES` is part of that infrastructure.

**Comment by ReimarBauer** [comment]
Our scheduled build runs in this problem on linux and MacOS

/home/runner/Miniforge/envs/mssenv/etc/conda/deactivate.d/libxml2_deactivate.sh: line 3: xml_catalog_files_libxml2: unbound variable

https://github.com/Open-MSS/mss-install/actions/runs/10035304064/job/27731093204#step:3:1200

**Comment by hattne** [comment]
> /home/runner/Miniforge/envs/mssenv/etc/conda/deactivate.d/libxml2_deactivate.sh: line 3: xml_catalog_files_libxml2: unbound variable

The unbound-variable issue in `libxml2_deactivate.sh` was addressed in b98cd64acb62999933100e288762fd275a947045.

It seems your build is pulling in `libxml2-2.10.3_4` on [line 971](https://github.com/Open-MSS/mss-install/actions/runs/10035304064/job/27731093204#step:3:972). I don't know what's causing that, but I suspect it's what's causing the breakage. You'll need `libxml2-2.10.3_6` or later for the fix.

**Comment by jakirkham** [comment]
Please open a new bug issue on the feedstock with all the info requested if you are still seeing issues

**Pull request merged**
