### PR TITLE
Fix run_exports

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
hmmm, are you suggesting repodata patching too?

**Comment by hmaarrfk** [comment]
do you have any justification as to why the analysis is incorrect beyond a hunch? 

is there a reference to some documentation upstream maybe?

**Comment by isuruf** [comment]
Running
```
nm -D /shared/home/idf2/miniforge3/lib/libxml2.so.2.11.6 | grep " T " | cut -b 20- | sort > 211.txt
nm -D /shared/home/idf2/miniforge3/envs/libxml2-212/lib/libxml2.so.2.12.2 | grep " T " | cut -b 20- | sort > 212.txt
diff -ru 211.txt 212.txt
```
gives me
```
--- 211.txt     2024-01-15 07:45:22.766443661 -0600
+++ 212.txt     2024-01-15 07:45:12.674166456 -0600
@@ -224,6 +224,7 @@
 xmlCheckFilename@@LIBXML2_2.4.30
 xmlCheckHTTPInput@@LIBXML2_2.6.0
 xmlCheckLanguageID@@LIBXML2_2.4.30
+xmlCheckThreadLocalStorage
 xmlCheckUTF8@@LIBXML2_2.4.30
 xmlCheckVersion@@LIBXML2_2.4.30
 xmlChildElementCount@@LIBXML2_2.7.3
@@ -277,6 +278,7 @@
 xmlCtxtResetLastError@@LIBXML2_2.6.0
 xmlCtxtReset@@LIBXML2_2.6.0
 xmlCtxtResetPush@@LIBXML2_2.6.1
+xmlCtxtSetMaxAmplification
 xmlCtxtUseOptions@@LIBXML2_2.6.0
 xmlCurrentChar@@LIBXML2_2.4.30
 xmlDebugCheckDocument@@LIBXML2_2.6.15
@@ -355,6 +357,7 @@
 xmlFreeElementContent@@LIBXML2_2.4.30
 xmlFreeElementTable@@LIBXML2_2.4.30
 xmlFreeEntitiesTable@@LIBXML2_2.4.30
+xmlFreeEntity
 xmlFreeEnumeration@@LIBXML2_2.4.30
 xmlFreeIDTable@@LIBXML2_2.4.30
 xmlFreeInputStream@@LIBXML2_2.4.30
@@ -746,6 +749,7 @@
 xmlParserInputBufferCreateIO@@LIBXML2_2.4.30
 xmlParserInputBufferCreateMem@@LIBXML2_2.4.30
 xmlParserInputBufferCreateStatic@@LIBXML2_2.6.0
+xmlParserInputBufferCreateString
 xmlParserInputBufferGrow@@LIBXML2_2.4.30
 xmlParserInputBufferPush@@LIBXML2_2.4.30
 xmlParserInputBufferRead@@LIBXML2_2.4.30
@@ -1130,6 +1134,7 @@
 xmlTextReaderSchemaValidateCtxt@@LIBXML2_2.6.23
 xmlTextReaderSchemaValidate@@LIBXML2_2.6.20
 xmlTextReaderSetErrorHandler@@LIBXML2_2.5.2
+xmlTextReaderSetMaxAmplification
 xmlTextReaderSetParserProp@@LIBXML2_2.5.0
 xmlTextReaderSetSchema@@LIBXML2_2.6.20
 xmlTextReaderSetStructuredErrorHandler@@LIBXML2_2.6.6
@@ -1607,5 +1612,23 @@
 xmlXPathWrapExternal@@LIBXML2_2.4.30
 xmlXPathWrapNodeSet@@LIBXML2_2.4.30
 xmlXPathWrapString@@LIBXML2_2.4.30
+xmlXPtrBuildNodeList@@LIBXML2_2.4.30
 xmlXPtrEval@@LIBXML2_2.4.30
+xmlXPtrFreeLocationSet@@LIBXML2_2.4.30
+xmlXPtrLocationSetAdd@@LIBXML2_2.4.30
+xmlXPtrLocationSetCreate@@LIBXML2_2.4.30
+xmlXPtrLocationSetDel@@LIBXML2_2.4.30
+xmlXPtrLocationSetMerge@@LIBXML2_2.4.30
+xmlXPtrLocationSetRemove@@LIBXML2_2.4.30
+xmlXPtrNewCollapsedRange@@LIBXML2_2.4.30
 xmlXPtrNewContext@@LIBXML2_2.4.30
+xmlXPtrNewLocationSetNodeSet@@LIBXML2_2.4.30
+xmlXPtrNewLocationSetNodes@@LIBXML2_2.4.30
+xmlXPtrNewRange@@LIBXML2_2.4.30
+xmlXPtrNewRangeNodeObject@@LIBXML2_2.4.30
+xmlXPtrNewRangeNodePoint@@LIBXML2_2.4.30
+xmlXPtrNewRangeNodes@@LIBXML2_2.4.30
+xmlXPtrNewRangePointNode@@LIBXML2_2.4.30
+xmlXPtrNewRangePoints@@LIBXML2_2.4.30
+xmlXPtrRangeToFunction@@LIBXML2_2.4.30
+xmlXPtrWrapLocationSet@@LIBXML2_2.4.30
```

which shows us that only symbols were added which shows us that the analysis in abi-laboratory is false and we were relying on that analysis.

We can trust the upstream maintainers of such a mature project to bump the major number/SOVERSION when there are breaking changes.

**Comment by isuruf** [comment]
See https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/634

**Comment by hmaarrfk** [comment]
Thank you for the thorough explination.

given neither of us are maintainers here, so how do you suggest we proceed? wait for a review?

**Comment by isuruf** [comment]
Yes, let's wait for @ocefpaf or someone from @conda-forge/libxml2

**Comment by ocefpaf** [comment]
Looks good to me!

**Comment by isuruf** [comment]
Thanks

**Comment by ocefpaf** [comment]
Thank you for fixing this. We fall into a comfort zone with our pins sometimes a d forget to review them.

**Pull request merged**
