### PR TITLE
Fix for previous pull request #82

### PR DESCRIPTION
**Pull request by celestino-amado**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by celestino-amado** [comment]
The previous pull request #82 is causing an issue on Windows OS: the Anaconda Prompt (cmd) started behaving not as expected when lauching and after using conda commands.

To fix it:

-  changed recipe/activate.bat to start lines 1 and 2 with @
    (used @set instead of set)
-  and changed recipe/desactivate.bat to start lines 1, 2, 4 and 6 with @
    (used @if instead of if and used @set instead of set)

**Comment by jakirkham** [comment]
cc @hattne @ocefpaf @isuruf

**Comment by ocefpaf** [comment]
@celestino-amado and @hattne we need to mark the previous builds as broken. See https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages

Do any of you want to try to send a PR to do that? If not I can do that later today.

**Comment by isuruf** [comment]
We should also fix https://github.com/conda-forge/libxml2-feedstock/pull/82#discussion_r1065733007 before merging this.

**Comment by celestino-amado** [comment]
> We should also fix [#82 (comment)](https://github.com/conda-forge/libxml2-feedstock/pull/82#discussion_r1065733007) before merging this.

Thanks! I had commented in #82 regarding this issue.

**Comment by celestino-amado** [comment]
I had closed this pull request since, as I commented in #82, it was made unclear for me the need to assign in Windows OS the environment variable `XML_CATALOG_FILES=/etc/xml/catalog`, because there is no xsltproc catalog folder `etc/xml/catalog` in Windows. The issue regarding #82 still persist.

**Comment by jakirkham** [comment]
> @celestino-amado and @hattne we need to mark the previous builds as broken. See https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages
> 
> Do any of you want to try to send a PR to do that? If not I can do that later today.

It's worth noting the packages haven't been produced yet due to token issues ( https://github.com/conda-forge/libxml2-feedstock/issues/83 ). That said, the token here has been reset. So rebuilding will produce packages (that will then have the issues noted)

**Comment by hattne** [comment]
> We should also fix [#82 (comment)](https://github.com/conda-forge/libxml2-feedstock/pull/82#discussion_r1065733007) before merging this.

I absolutely agree, but it seems to me there is more serious breakage elsewhere. I'd like to test my patch a bit more carefully this time…

**Pull request closed without merging**
