### PR TITLE
iconv is referred to in the build.sh

### LINKED ISSUE #35: Build inconsistency
linux build in build.sh uses a --with-iconv but excludes it in meta.yaml

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

Closes #35

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by ocefpaf** [comment]
@mariusvniekerk are you experiencing issues with the lack of `libiconv`? Folks in AnacondaRecipes are no longer using it on Linux but rather relying on the version present on the system. See https://github.com/AnacondaRecipes/libxml2-feedstock/blob/master/recipe/meta.yaml#L32

Ping @msarahan

**Comment by mariusvniekerk** [comment]
Basically this makes lxml not work which breaks some downstream things

**Comment by ocefpaf** [comment]
> Basically this makes lxml not work which breaks some downstream things

It is working for me and some things downstream may need to be rebuilt.
Let's coordinate this with @msarahan to avoid drifting the recipe in a matter that may have more than one solution.

**Comment by mariusvniekerk** [comment]
I think the previos master lxml pulled in the version of libxml2 prior to this change

**Comment by ocefpaf** [comment]
> I think the previos master lxml pulled in the version of libxml2 prior to this change

Probably. I already had to rebuild some things b/c of this change.

**Comment by ocefpaf** [comment]
> The other solution may be to remove the --with-iconv="${PREFIX}" line from the build.sh under linux

I don't think we need to do that b/c iconv **is** present in all Linuxes, we should be OK by not relying on our old build.

**Comment by ocefpaf** [comment]
@mariusvniekerk I changed my mind b/c to do this properly we would need to get rid of `libconv` in all the dependencies in `conda-forge` and there are many: https://github.com/search?l=YAML&p=1&q=org%3Aconda-forge+libiconv&type=Code

In fact, `libiconv` made its way into `Python` itself so we have to either merge this or remove `--with-iconv="${PREFIX}"`. I will merge this to fix the current broken situation and we can talk about a long term strategy later. Thanks!

**Pull request merged**
