### PR TITLE
Enable thread-local storage support

### LINKED ISSUE #117: libxml2 is compiled with thread-local storage disabled
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

[Starting with 2.12.0](https://discourse.gnome.org/t/libxml2-2-12-0-released/18063/1), libxml2 is able to make use of native thread-local storage on modern platforms. But it seems that, for it to be enabled, the [`--with-tls`](https://gitlab.gnome.org/GNOME/libxml2/-/blob/20b0bd9800ae83cbd70f4407ce67058164e16227/configure.ac#L138-139) flag has to be given to the configure script.

conda-forge's libxml2 does not seem to have thread-local storage enabled, as can be seen when disassembling the [`xmlGetThreadLocalStorage` function](https://gitlab.gnome.org/GNOME/libxml2/-/blob/f907f785cee6d850b937bf1f1bced1fbc88c6cb5/globals.c#L869-892) (there's a call to `pthread_getspecific` which wouldn't be there otherwise):

```dis
000000000003f510 <xmlGetThreadLocalStorage>:
   3f510:	       55                   	push   %rbp
   3f511:	       89 fd                	mov    %edi,%ebp
   3f513:	       53                   	push   %rbx
   3f514:	       48 83 ec 08          	sub    $0x8,%rsp
   3f518:	       8b 3d 4a 83 12 00    	mov    0x12834a(%rip),%edi        # 167868 <globalkey>
   3f51e:	       ff 15 9c 65 12 00    	call   *0x12659c(%rip)        # 165ac0 <pthread_getspecific@Base>
   3f524:	       48 89 c3             	mov    %rax,%rbx
   3f527:	       48 85 c0             	test   %rax,%rax
   3f52a:	   /-- 74 14                	je     3f540 <xmlGetThreadLocalStorage+0x30>
   3f52c:	/--|-> 48 83 c4 08          	add    $0x8,%rsp
   3f530:	|  |   48 89 d8             	mov    %rbx,%rax
   3f533:	|  |   5b                   	pop    %rbx
   3f534:	|  |   5d                   	pop    %rbp
   3f535:	|  |   c3                   	ret    
   3f536:	|  |   66 2e 0f 1f 84 00 00 	cs nopw 0x0(%rax,%rax,1)
   3f53d:	|  |   00 00 00 
   3f540:	|  \-> be 01 00 00 00       	mov    $0x1,%esi
   3f545:	|      bf c8 02 00 00       	mov    $0x2c8,%edi
   3f54a:	|      ff 15 60 72 12 00    	call   *0x127260(%rip)        # 1667b0 <calloc@GLIBC_2.2.5>
   3f550:	|      48 89 c3             	mov    %rax,%rbx
   3f553:	|      48 85 c0             	test   %rax,%rax
   3f556:	|  /-- 0f 84 9a 01 00 00    	je     3f6f6 <xmlGetThreadLocalStorage+0x1e6>
   3f55c:	|  |   48 8d 2d 1d 83 12 00 	lea    0x12831d(%rip),%rbp        # 167880 <xmlThrDefMutex>
   3f563:	|  |   48 89 ef             	mov    %rbp,%rdi
   3f566:	|  |   ff 15 84 75 12 00    	call   *0x127584(%rip)        # 166af0 <xmlMutexLock@@LIBXML2_2.4.30+0x105bf0>
   3f56c:	|  |   48 8d bb 80 00 00 00 	lea    0x80(%rbx),%rdi
   3f573:	|  |   ff 15 3f 74 12 00    	call   *0x12743f(%rip)        # 1669b8 <inithtmlDefaultSAXHandler@@LIBXML2_2.4.30+0xc7ad8>
   3f579:	|  |   8b 05 d5 7d 12 00    	mov    0x127dd5(%rip),%eax        # 167354 <xmlBufferAllocSchemeThrDef>
   3f57f:	|  |   be 01 00 00 00       	mov    $0x1,%esi
   3f584:	|  |   48 8d bb d0 01 00 00 	lea    0x1d0(%rbx),%rdi
   3f58b:	|  |   c7 83 70 01 00 00 00 	movl   $0x0,0x170(%rbx)
   3f592:	|  |   00 00 00 
   3f595:	|  |   89 83 b0 02 00 00    	mov    %eax,0x2b0(%rbx)
   3f59b:	|  |   8b 05 ab 7d 12 00    	mov    0x127dab(%rip),%eax        # 16734c <xmlDefaultBufferSizeThrDef>
   3f5a1:	|  |   89 83 b4 02 00 00    	mov    %eax,0x2b4(%rbx)
   3f5a7:	|  |   ff 15 fb 79 12 00    	call   *0x1279fb(%rip)        # 166fa8 <initxmlDefaultSAXHandler@@LIBXML2_2.4.30+0xc81f8>
   3f5ad:	|  |   8b 05 81 7d 12 00    	mov    0x127d81(%rip),%eax        # 167334 <xmlIndentTreeOutputThrDef>
   3f5b3:	|  |   f3 0f 7e 05 45 64 12 	movq   0x126445(%rip),%xmm0        # 165a00 <xmlSAX2GetPublicId@@LIBXML2_2.6.0+0x104fb0>
   3f5ba:	|  |   00 
   3f5bb:	|  |   48 8d 53 08          	lea    0x8(%rbx),%rdx
   3f5bf:	|  |   66 0f 6e 1d 81 82 12 	movd   0x128281(%rip),%xmm3        # 167848 <xmlSubstituteEntitiesDefaultValueThrDef>
   3f5c6:	|  |   00 
   3f5c7:	|  |   66 0f 6e 25 8d 82 12 	movd   0x12828d(%rip),%xmm4        # 16785c <xmlParserDebugEntitiesThrDef>
   3f5ce:	|  |   00 
   3f5cf:	|  |   48 89 d7             	mov    %rdx,%rdi
   3f5d2:	|  |   b9 0b 00 00 00       	mov    $0xb,%ecx
   3f5d7:	|  |   89 83 b8 01 00 00    	mov    %eax,0x1b8(%rbx)
   3f5dd:	|  |   48 8b 05 7c 7f 12 00 	mov    0x127f7c(%rip),%rax        # 167560 <xmlTreeIndentStringThrDef>
   3f5e4:	|  |   0f 16 05 05 69 12 00 	movhps 0x126905(%rip),%xmm0        # 165ef0 <xmlSAX2GetSystemId@@LIBXML2_2.6.0+0x105490>
   3f5eb:	|  |   0f 11 83 78 01 00 00 	movups %xmm0,0x178(%rbx)
   3f5f2:	|  |   66 0f 6e 0d 56 82 12 	movd   0x128256(%rip),%xmm1        # 167850 <xmlPedanticParserDefaultValueThrDef>
   3f5f9:	|  |   00 
   3f5fa:	|  |   f3 0f 7e 05 76 56 12 	movq   0x125676(%rip),%xmm0        # 164c78 <xmlSAX2GetLineNumber@@LIBXML2_2.6.0+0x1041f8>
   3f601:	|  |   00 
   3f602:	|  |   48 89 83 c0 01 00 00 	mov    %rax,0x1c0(%rbx)
   3f609:	|  |   8b 05 fd 81 12 00    	mov    0x1281fd(%rip),%eax        # 16780c <xmlSaveNoEmptyTagsThrDef>
   3f60f:	|  |   0f 16 05 fa 5e 12 00 	movhps 0x125efa(%rip),%xmm0        # 165510 <xmlSAX2GetColumnNumber@@LIBXML2_2.6.0+0x104a70>
   3f616:	|  |   66 0f 62 cb          	punpckldq %xmm3,%xmm1
   3f61a:	|  |   66 0f 6e 2d 2a 82 12 	movd   0x12822a(%rip),%xmm5        # 16784c <xmlLineNumbersDefaultValueThrDef>
   3f621:	|  |   00 
   3f622:	|  |   66 0f 6e 35 1a 7d 12 	movd   0x127d1a(%rip),%xmm6        # 167344 <xmlGetWarningsDefaultValueThrDef>
   3f629:	|  |   00 
   3f62a:	|  |   89 83 c8 01 00 00    	mov    %eax,0x1c8(%rbx)
   3f630:	|  |   48 8b 05 39 7f 12 00 	mov    0x127f39(%rip),%rax        # 167570 <xmlGenericErrorThrDef>
   3f637:	|  |   0f 11 83 88 01 00 00 	movups %xmm0,0x188(%rbx)
   3f63e:	|  |   66 0f 6e 05 0e 82 12 	movd   0x12820e(%rip),%xmm0        # 167854 <xmlLoadExtDtdDefaultValueThrDef>
   3f645:	|  |   00 
   3f646:	|  |   66 0f 6e 15 ee 7c 12 	movd   0x127cee(%rip),%xmm2        # 16733c <xmlKeepBlanksDefaultValueThrDef>
   3f64d:	|  |   00 
   3f64e:	|  |   48 89 43 60          	mov    %rax,0x60(%rbx)
   3f652:	|  |   48 8b 05 c7 81 12 00 	mov    0x1281c7(%rip),%rax        # 167820 <xmlStructuredErrorThrDef>
   3f659:	|  |   66 0f 62 c4          	punpckldq %xmm4,%xmm0
   3f65d:	|  |   66 0f 62 d5          	punpckldq %xmm5,%xmm2
   3f661:	|  |   48 89 43 70          	mov    %rax,0x70(%rbx)
   3f665:	|  |   66 0f 6c c1          	punpcklqdq %xmm1,%xmm0
   3f669:	|  |   48 8b 05 a8 81 12 00 	mov    0x1281a8(%rip),%rax        # 167818 <xmlGenericErrorContextThrDef>
   3f670:	|  |   66 0f 6e 0d e0 81 12 	movd   0x1281e0(%rip),%xmm1        # 167858 <xmlDoValidityCheckingDefaultValueThrDef>
   3f677:	|  |   00 
   3f678:	|  |   0f 11 83 a8 01 00 00 	movups %xmm0,0x1a8(%rbx)
   3f67f:	|  |   f3 0f 7e 05 b9 81 12 	movq   0x1281b9(%rip),%xmm0        # 167840 <xmlRegisterNodeDefaultValueThrDef>
   3f686:	|  |   00 
   3f687:	|  |   48 89 43 68          	mov    %rax,0x68(%rbx)
   3f68b:	|  |   48 8b 05 7e 81 12 00 	mov    0x12817e(%rip),%rax        # 167810 <xmlStructuredErrorContextThrDef>
   3f692:	|  |   66 0f 62 ce          	punpckldq %xmm6,%xmm1
   3f696:	|  |   0f 16 05 9b 81 12 00 	movhps 0x12819b(%rip),%xmm0        # 167838 <xmlDeregisterNodeDefaultValueThrDef>
   3f69d:	|  |   66 0f 6c ca          	punpcklqdq %xmm2,%xmm1
   3f6a1:	|  |   48 89 43 78          	mov    %rax,0x78(%rbx)
   3f6a5:	|  |   31 c0                	xor    %eax,%eax
   3f6a7:	|  |   0f 11 8b 98 01 00 00 	movups %xmm1,0x198(%rbx)
   3f6ae:	|  |   0f 11 83 b8 02 00 00 	movups %xmm0,0x2b8(%rbx)
   3f6b5:	|  |   f3 0f 7e 05 73 81 12 	movq   0x128173(%rip),%xmm0        # 167830 <xmlParserInputBufferCreateFilenameValueThrDef>
   3f6bc:	|  |   00 
   3f6bd:	|  |   0f 16 05 64 81 12 00 	movhps 0x128164(%rip),%xmm0        # 167828 <xmlOutputBufferCreateFilenameValueThrDef>
   3f6c4:	|  |   0f 11 83 60 01 00 00 	movups %xmm0,0x160(%rbx)
   3f6cb:	|  |   f3 48 ab             	rep stos %rax,%es:(%rdi)
   3f6ce:	|  |   48 89 ef             	mov    %rbp,%rdi
   3f6d1:	|  |   ff 15 39 70 12 00    	call   *0x127039(%rip)        # 166710 <xmlMutexUnlock@@LIBXML2_2.4.30+0x1057f0>
   3f6d7:	|  |   48 89 de             	mov    %rbx,%rsi
   3f6da:	|  |   8b 3d 88 81 12 00    	mov    0x128188(%rip),%edi        # 167868 <globalkey>
   3f6e0:	|  |   ff 15 82 77 12 00    	call   *0x127782(%rip)        # 166e68 <pthread_setspecific@Base>
   3f6e6:	|  |   c7 03 01 00 00 00    	movl   $0x1,(%rbx)
   3f6ec:	|  |   48 83 c4 08          	add    $0x8,%rsp
   3f6f0:	|  |   48 89 d8             	mov    %rbx,%rax
   3f6f3:	|  |   5b                   	pop    %rbx
   3f6f4:	|  |   5d                   	pop    %rbp
   3f6f5:	|  |   c3                   	ret    
   3f6f6:	|  \-> 85 ed                	test   %ebp,%ebp
   3f6f8:	\----- 0f 85 2e fe ff ff    	jne    3f52c <xmlGetThreadLocalStorage+0x1c>
   3f6fe:	       48 8b 05 13 73 12 00 	mov    0x127313(%rip),%rax        # 166a18 <stderr@GLIBC_2.2.5>
   3f705:	       ba 57 00 00 00       	mov    $0x57,%edx
   3f70a:	       be 01 00 00 00       	mov    $0x1,%esi
   3f70f:	       48 8d 3d 62 57 0d 00 	lea    0xd5762(%rip),%rdi        # 114e78 <CSWTCH.255+0x258>
   3f716:	       48 8b 08             	mov    (%rax),%rcx
   3f719:	       ff 15 39 74 12 00    	call   *0x127439(%rip)        # 166b58 <fwrite@GLIBC_2.2.5>
   3f71f:	       ff 15 eb 58 12 00    	call   *0x1258eb(%rip)        # 165010 <abort@GLIBC_2.2.5>
```

The reason this came up is that this might the cause of Valgrind failures we're seeing on Arrow's CI jobs:
https://github.com/apache/arrow/issues/41004

Specifically, the [`xmlNewGlobalState`](https://gitlab.gnome.org/GNOME/libxml2/-/blob/f907f785cee6d850b937bf1f1bced1fbc88c6cb5/globals.c#L834-866) function that gets invoked in the legacy path does a malloc that's potentially never freed later.

### Installed packages

```shell
# packages in environment at /opt/conda/envs/arrow:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
protobuf                  4.24.3                   pypi_0    pypi
python                    3.10.14         hd12c33a_0_cpython    conda-forge
rapidjson                 1.1.0             he1b5a44_1002    conda-forge
rdma-core                 50.0                 hd3aeb46_1    conda-forge
re2                       2022.06.01           h27087fc_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
rhash                     1.4.4                hd590300_0    conda-forge
s2n                       1.3.51               h06160fa_0    conda-forge
scalpl                    0.4.2                    pypi_0    pypi
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sysroot_linux-64          2.12                he073ed8_17    conda-forge
thrift-compiler           0.19.0               h59595ed_1    conda-forge
thrift-cpp                0.19.0               ha770c72_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucx                       1.15.0               h11edf95_7    conda-forge
ucx-proc                  1.0.0                       cpu    conda-forge
urllib3                   2.2.1                    pypi_0    pypi
valgrind                  3.22.0               hcd5def8_1    conda-forge
waitress                  2.1.2                    pypi_0    pypi
werkzeug                  3.0.0                    pypi_0    pypi
wheel                     0.43.0             pyhd8ed1ab_0    conda-forge
xsimd                     12.1.1               h00ab1b0_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

### Environment info

```shell
Not available, but should be irrelevant.
```

### PR DESCRIPTION
**Pull request by kou**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

fix #117

It's available since libxml2 2.12.0.
See also: https://discourse.gnome.org/t/libxml2-2-12-0-released/18063

### CODE REVIEW

**Comment by gillins** [comment]
Thanks @kou. Is there an equivalent change for Windows?
Also - is is possible to add a test that this has indeed worked?
Lastly, can you confirm that there are no changes to the symbol names with this change...

**Comment by kou** [comment]
> Is there an equivalent change for Windows?

I thought that it's needless because `threads=native` is the default: https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/win32/configure.js#L31
But it seems that we need to specify `threads=ctls`: https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/win32/Makefile.msvc#L51-52

I've added it.

> is is possible to add a test that this has indeed worked?

Can we download built binaries? I want them to think about how to test.

> can you confirm that there are no changes to the symbol names with this change.

I want built binaries for this too.

**Comment by gillins** [comment]
Thanks!

> Can we download built binaries?

See https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure - seems that `store_build_artifacts` under `azure` is what you are after. Not sure where it will put it, but I hope it might print this in the logs....

**Comment by kou** [comment]
Thanks. I've enabled `azure.store_build_artifacts` but I couldn't find Azure pipeline artifact location... Where...?

**Comment by gillins** [comment]
Trying this to see if it helps. @conda-forge-admin, please rerender

**Comment by gillins** [comment]
@kou can you access https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=915425&view=artifacts&pathAsName=false&type=publishedArtifacts ?

**Comment by kou** [comment]
Yes! Thanks!
BTW, how did you find the URL...?

**Comment by kou** [comment]
No symbol name changes. There are only changes related to glibc. 

```console
$ diff -u <(nm --extern-only built/libxml2.so.2.12.6 | sed -e 's/^[0-f ]*//g') <(nm --extern-only released/libxml2.so | sed -e 's/^[0-f ]*//g') 
--- /proc/self/fd/12	2024-04-16 14:30:03.716588471 +0900
+++ /proc/self/fd/14	2024-04-16 14:30:03.716588471 +0900
@@ -66,7 +66,6 @@
 stack_chk_fail@GLIBC_2.4
 stpcpy_chk@GLIBC_2.3.4
 strcat_chk@GLIBC_2.3.4
-tls_get_addr@GLIBC_2.3
 vfprintf_chk@GLIBC_2.3.4
 vsnprintf_chk@GLIBC_2.3.4
 xmlBufferAllocScheme
@@ -99,10 +98,12 @@
 xstat64@GLIBC_2.2.5
 ini
 init
+ort@GLIBC_2.2.5
 ttribute
 ttributeDecl
 ind@GLIBC_2.2.5
 search@GLIBC_2.2.5
+lloc@GLIBC_2.2.5
 taBlock
 haracters
 heckNamespace
```

**Comment by gillins** [comment]
That is good news!
I found the link by going into the logs for one of the builds (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=915425&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) and clicking on the `1 artifact` link. Not sure if there is a better way.

**Comment by kou** [comment]
We can check whether `--with-tls` is enabled or not by `nm lib/libxml2.so.2.12.6 | grep globalState` but I think that it's too depending on implementation details... Is it OK?

**Comment by kou** [comment]
> I found the link by going into the logs for one of the builds (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=915425&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) and clicking on the `1 artifact` link.

Wow! I didn't notice it!

**Comment by gillins** [comment]
> We can check whether --with-tls is enabled or not by nm lib/libxml2.so.2.12.6 | grep globalState

Yeah that is a bit obscure, likely to change and platform specific. If there is no other easy way to test I guess we merge it hope this feature doesn't get lost by changes down the track. What do you think @conda-forge/libxml2 ?

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please restart ci​

**Comment by gillins** [comment]
Thanks @kou !

**Comment by kou** [comment]
Thanks! I'll try this change in apache/arrow.

**Pull request merged**
